# Generated by Django 5.1.2 on 2024-11-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration_movie',
        ),
    ]
